service: frontend

plugins:
  - serverless-finch

custom:
  client:
    bucketName: serverless-demo-frontend-${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  profile: serverless-demo
