service: film-backend

custom:
  config: ${file(config/${opt:stage, "dev"}.yml)}
  env_specific_variable: ${self:custom.config.ENV_SPECIFIC_VARIABLE}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: serverless-demo
  stackTags:
    author: myself
    environment: ${opt:stage, self:provider.stage}
    product: ${self:service}

package: # Optional deployment packaging configuration
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - spec/
  excludeDevDependencies: false # Config if Serverless should automatically exclude dev dependencies in the deployment package. Defaults to true

functions:
  getFilms:
    handler: handler.lambda
    name: ${self:provider.stage}-getFilms
    events:
      - http:
          path: films
          method: get
          cors: true
